# Generated by Django 5.1.4 on 2025-01-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captive',
            name='appearance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='circumstances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='found_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='person_type',
            field=models.CharField(choices=[('military', 'Військовий'), ('civilian', 'Цивільний')], default='civilian', max_length=10),
        ),
        migrations.AddField(
            model_name='captive',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='settlement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='captive',
            name='status',
            field=models.CharField(choices=[('searching', 'Розшукується'), ('found', 'Знайдено (чекає рідних)'), ('reunited', 'Зустрілися з рідними')], default='searching', max_length=20),
        ),
        migrations.AlterField(
            model_name='captive',
            name='brigade',
            field=models.CharField(blank=True, help_text='Заповнюється тільки для військових', max_length=100, null=True),
        ),
    ]
