# Generated by Django 5.1.4 on 2025-01-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_captive_appearance_captive_circumstances_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captive',
            old_name='found_date',
            new_name='last_update',
        ),
        migrations.RemoveField(
            model_name='captive',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='captive',
            name='status',
            field=models.CharField(choices=[('searching', 'Розшукується'), ('informed', 'Є інформація'), ('reunited', 'Зустрілися з рідними')], default='searching', max_length=20),
        ),
    ]
