# Generated by Django 5.1.4 on 2025-04-22 09:30

import backend.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_rename_found_date_captive_last_update_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="captive",
            name="picture_embedded",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="captive",
            name="last_update",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="captive",
            name="name",
            field=models.CharField(
                blank=True, default="Безіменний", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="captive",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=backend.models.get_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="captive",
            name="status",
            field=models.CharField(
                choices=[
                    ("searching", "Розшукується"),
                    ("informed", "Є інформація"),
                    ("reunited", "Зустрілися з рідними"),
                    ("deceased", "Помер"),
                ],
                default="searching",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="captive",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
