# Generated by Django 5.1.4 on 2025-04-22 09:30
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_captive_appearance_embedded_captive_picture_embedded_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="captive",
            name="appearance_embedded",
            field=models.TextField(blank=True, null=True),
        ),
    ]
